# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: NHLTracker_development
  host: localhost

test:
  adapter: postgresql
  database: NHLTracker_test
  host: localhost

production:
  adapter: postgresql
  database: NHLTracker
  host: localhost